AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - .gems/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/IndentationWidth:
  Width: 2

Style/NestedParenthesizedCalls:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: true

Style/EmptyLinesAroundClassBody:
  Enabled: true

Style/EmptyLinesAroundModuleBody:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: key

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Alias:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 10

Metrics/AbcSize:
  Max: 30

Lint/UnderscorePrefixedVariableName:
  Enabled: false
